In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_table('C:/Users/user/Desktop/BA/ML/Germandata.txt',header=None,sep=' ')

In [4]:
data.head()

0   1    2    3     4    5    6   7    8     9  ...    11  12    13    14  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101 ...  A121  67  A143  A152   
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101 ...  A121  22  A143  A152   
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101 ...  A121  49  A143  A152   
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103 ...  A122  45  A143  A153   
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101 ...  A124  53  A143  A153   

  15    16 17    18    19 20  
0  2  A173  1  A192  A201  1  
1  1  A173  1  A191  A201  2  
2  1  A172  2  A191  A201  1  
3  1  A173  2  A191  A201  1  
4  2  A173  2  A191  A201  2  

[5 rows x 21 columns]

In [5]:
data.shape

(1000, 21)

In [6]:
names=['V'+str(i) for i in range(1,21)]

In [7]:
names.append('class')

In [8]:
data.columns=names

In [9]:
data.head()

V1  V2   V3   V4    V5   V6   V7  V8   V9   V10  ...    V12 V13   V14  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101  ...   A121  67  A143   
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101  ...   A121  22  A143   
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101  ...   A121  49  A143   
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103  ...   A122  45  A143   
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101  ...   A124  53  A143   

    V15 V16   V17 V18   V19   V20 class  
0  A152   2  A173   1  A192  A201     1  
1  A152   1  A173   1  A191  A201     2  
2  A152   1  A172   2  A191  A201     1  
3  A153   1  A173   2  A191  A201     1  
4  A153   2  A173   2  A191  A201     2  

[5 rows x 21 columns]

In [12]:
data.dtypes

V1       object
V2        int64
V3       object
V4       object
V5        int64
V6       object
V7       object
V8        int64
V9       object
V10      object
V11       int64
V12      object
V13       int64
V14      object
V15      object
V16       int64
V17      object
V18       int64
V19      object
V20      object
class     int64
dtype: object

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
V1       1000 non-null object
V2       1000 non-null int64
V3       1000 non-null object
V4       1000 non-null object
V5       1000 non-null int64
V6       1000 non-null object
V7       1000 non-null object
V8       1000 non-null int64
V9       1000 non-null object
V10      1000 non-null object
V11      1000 non-null int64
V12      1000 non-null object
V13      1000 non-null int64
V14      1000 non-null object
V15      1000 non-null object
V16      1000 non-null int64
V17      1000 non-null object
V18      1000 non-null int64
V19      1000 non-null object
V20      1000 non-null object
class    1000 non-null int64
dtypes: int64(8), object(13)
memory usage: 164.1+ KB


In [14]:
data.isnull().sum()

V1       0
V2       0
V3       0
V4       0
V5       0
V6       0
V7       0
V8       0
V9       0
V10      0
V11      0
V12      0
V13      0
V14      0
V15      0
V16      0
V17      0
V18      0
V19      0
V20      0
class    0
dtype: int64

# Encoding categorical variables

#### Categorical data can either be Ordinal or Nominal. 
##### Ordinal --> LabelEncoding
##### Nominal --> One hot encoding (i.e. dummy variables)

### When to normalize the dtatset? Should we normalize this dataset?

#### Answer: <br>
It depends on the model. <br>
If you are going to use a model where distances like Euclidean distances are coming into the picture, for example, models like KNN, then NORMALIZATION of the dataset is ESSENTIAL. ,br>
But if we are goingto use a model, like Decision Trees, which is not based on distance calculations then we Do NOT NEED to normalize the dataset. <br>
(Note: DTs use entropy and gain to do classification which are probabilities and thus distances dont come into picture here)

In [15]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [16]:
le=LabelEncoder()

In [18]:
data.V1.dtypes

dtype('O')

In [21]:
cat_var=[]
num_var=[]
for col in data.columns:
    if data[col].dtypes=='O':
        cat_var.append(col)
    else:
        num_var.append(col)

In [22]:
cat_var

['V1',
 'V3',
 'V4',
 'V6',
 'V7',
 'V9',
 'V10',
 'V12',
 'V14',
 'V15',
 'V17',
 'V19',
 'V20']

In [23]:
num_var

['V2', 'V5', 'V8', 'V11', 'V13', 'V16', 'V18', 'class']

In [24]:
cat_data=data[cat_var]
num_data=data[num_var]

In [25]:
cat_data.head()

V1   V3   V4   V6   V7   V9   V10   V12   V14   V15   V17   V19   V20
0  A11  A34  A43  A65  A75  A93  A101  A121  A143  A152  A173  A192  A201
1  A12  A32  A43  A61  A73  A92  A101  A121  A143  A152  A173  A191  A201
2  A14  A34  A46  A61  A74  A93  A101  A121  A143  A152  A172  A191  A201
3  A11  A32  A42  A61  A74  A93  A103  A122  A143  A153  A173  A191  A201
4  A11  A33  A40  A61  A73  A93  A101  A124  A143  A153  A173  A191  A201

In [26]:
num_data.head()

V2    V5  V8  V11  V13  V16  V18  class
0   6  1169   4    4   67    2    1      1
1  48  5951   2    2   22    1    1      2
2  12  2096   2    3   49    1    2      1
3  42  7882   2    4   45    1    2      1
4  24  4870   3    4   53    2    2      2

In [27]:
xx=cat_data.apply(lambda x:le.fit_transform(x),axis=0)

In [28]:
xx.head()

V1  V3  V4  V6  V7  V9  V10  V12  V14  V15  V17  V19  V20
0   0   4   4   4   4   2    0    0    2    1    2    1    0
1   1   2   4   0   2   1    0    0    2    1    2    0    0
2   3   4   7   0   3   2    0    0    2    1    1    0    0
3   0   2   3   0   3   2    2    1    2    2    2    0    0
4   0   3   0   0   2   2    0    3    2    2    2    0    0

In [29]:
xx['V1'].value_counts()

3    394
0    274
1    269
2     63
Name: V1, dtype: int64

In [30]:
data_encoded=pd.concat([xx,num_data],axis=1)

In [31]:
data_encoded.head()

V1  V3  V4  V6  V7  V9  V10  V12  V14  V15  ...    V19  V20  V2    V5  V8  \
0   0   4   4   4   4   2    0    0    2    1  ...      1    0   6  1169   4   
1   1   2   4   0   2   1    0    0    2    1  ...      0    0  48  5951   2   
2   3   4   7   0   3   2    0    0    2    1  ...      0    0  12  2096   2   
3   0   2   3   0   3   2    2    1    2    2  ...      0    0  42  7882   2   
4   0   3   0   0   2   2    0    3    2    2  ...      0    0  24  4870   3   

   V11  V13  V16  V18  class  
0    4   67    2    1      1  
1    2   22    1    1      2  
2    3   49    1    2      1  
3    4   45    1    2      1  
4    4   53    2    2      2  

[5 rows x 21 columns]

In [32]:
type(data_encoded)

pandas.core.frame.DataFrame

In [50]:
data_encoded['class']=np.where(data_encoded['class']==1,0,1)
data_encoded['class'].head()

0    0
1    1
2    0
3    0
4    1
Name: class, dtype: int32

# Decision tree model 

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [37]:
tree_classifier=DecisionTreeClassifier()

In [52]:
cross_val_score(tree_classifier,X=data_encoded.iloc[:,:20],y=data_encoded['class'],n_jobs=4,cv=5)

array([0.635, 0.725, 0.67 , 0.685, 0.695])

In [53]:
cross_val_score(tree_classifier,X=data_encoded.iloc[:,:20],y=data_encoded['class'],n_jobs=4,cv=5).mean()

0.6849999999999999

In [42]:
cross_val_score(tree_classifier,X=data_encoded.iloc[:,:20],y=data_encoded['class'],scoring='roc_auc',n_jobs=4,cv=5)

array([0.57380952, 0.65833333, 0.6202381 , 0.64285714, 0.64285714])

In [54]:
# Receiver Operating Characteristic Curve (ROC)

In [43]:
cross_val_score(tree_classifier,X=data_encoded.iloc[:,:20],y=data_encoded['class'],scoring='roc_auc',n_jobs=4,cv=5).mean()

0.6328571428571428

In [44]:
## AUC= Area under the curve
## AUC of 60-65% is acceptable in the industry

In [46]:
params={'criterion':['entropy','gini'],'max_depth':[3,5,7,9]}  #grid of 8 values

In [49]:
best_tree=GridSearchCV(tree_classifier,param_grid=params,scoring='roc_auc',cv=5,n_jobs=-1)  #n_jobs = -1 means ALL Available scores

#### Note: <br>
GridSearchCV searches the grid of 'params' which has 8 values in it. <br>
 'params' has max_depth of [3,5,7,9] because we want to limit the DT at max 3,5,7 and at 9. <br>
 GridSeacrhCV checks the cross validation score of all 8 values and returns the one with best Cross Validation Score.

In [55]:
best_tree.fit(data_encoded.iloc[:,:20],data_encoded['class'])

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'criterion': ['entropy', 'gini'], 'max_depth': [3, 5, 7, 9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=0)

In [57]:
cross_val_score(best_tree,X=data_encoded.iloc[:,:20],scoring='roc_auc',y=data_encoded['class'],n_jobs=4,cv=5)

array([0.72839286, 0.72083333, 0.77541667, 0.68494048, 0.72416667])

In [58]:
cross_val_score(best_tree,X=data_encoded.iloc[:,:20],scoring='roc_auc',y=data_encoded['class'],n_jobs=4,cv=5).mean()

0.7315476190476191

In [59]:
best_tree.best_params_

{'criterion': 'gini', 'max_depth': 5}

In [60]:
from sklearn.metrics import make_scorer,cohen_kappa_score

In [64]:
cost_matrix=np.array([[0,1],[5,0]])
cost_matrix

array([[0, 1],
       [5, 0]])

In [63]:
confusion_mat=np.array([[20,5],[10,12]])
confusion_mat

array([[20,  5],
       [10, 12]])

In [65]:
cost_matrix*confusion_mat

array([[ 0,  5],
       [50,  0]])

In [66]:
np.sum(cost_matrix*confusion_mat)

55

In [67]:
np.sum(cost_matrix*confusion_mat)*(-1)

-55

In [71]:
def my_score(y_pred,y,**kwargs):
    c=confusion_mat(y,y_pred)
    score=np.sum(cost_matrix*c)*(-1)
    return score

Scorer=make_scorer(my_score)

def kappa(y_pred,y,**kwargs):
    return cohen_kappa_score(y,y_pred)

myKappa=make_scorer(kappa)

In [72]:
best_tree=GridSearchCV(tree_classifier,param_grid=params,scoring=Scorer,cv=5,n_jobs=-1)

In [ ]:
best_tree.fit(data_encoded.iloc[:,:20],data_encoded['class'])

In [ ]:
cross_val_score(tree_classifier,X=credit_data_encoded.iloc[:,:20],y=credit_data_encoded['class'],scoring=scorer,n_jobs=4, cv=5)

In [ ]:
best_tree = GridSearchCV(tree_classifier, param_grid = params, scoring= kappa, cv=5, n_jobs=-1)

In [ ]:
best_tree.fit(credit_data_encoded.iloc[:,:20],credit_data_encoded['class'])

In [ ]:
cross_val_score(tree_classifier,X=credit_data_encoded.iloc[:,:20],y=credit_data_encoded['class'],scoring=kappa,n_jobs=4, cv=5)